# Hugo.toml

baseURL = "https://nabilbinbillal.github.io/blog/"
languageCode = "en-us"
title = "Nabil Bin Billal's Blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "blog"  # Set the output directory to /blog

[params]
  author = "Nabil Bin Billal"
  description = "Exploring technology, science, education, and the world."
  github = "nabilbinbillal"
  facebook = "nabilbinbillal"
  twitter = "nabilbinbillal"
  linkedin = "nabilbinbillal"
  instagram = "nabilbinbillal"
  tumblr = "nabilbinbillal"
  email = "nabilbinbillal@gmail.com"
  url = "https://nabilbinbillal.github.io/blog"
  keywords = "blog, technology, science, education, environment"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "https://nabilbinbillal.github.io/jsm-logo.png"
  avatar = "https://nabilbinbillal.github.io/jsm-logo.png"
  headerIcon = "https://nabilbinbillal.github.io/favicon-32x32.png"
  location = "Bangladesh"
  enableGitalk = true

[params.gitalk]
  clientID = "Iv23liyUlkxsrnnAAk6d"
  clientSecret = "627091c057dfa858b73e2c1c8c667f5b38e11e12"  # Replace with your actual client secret
  repo = "nabilbinbillal.github.io"
  owner = "nabilbinbillal"
  admin = "nabilbinbillal"
  id = "location.pathname"
  labels = "gitalk"
  perPage = 15
  pagerDirection = "last"
  createIssueManually = true
  distractionFreeMode = false

[[params.links]]
  title = "GitHub"
  href = "https://github.com/nabilbinbillal"

[[params.links]]
  title = "Portfolio"
  href = "https://nabil.bidibo.xyz"
  icon = "https://nabilbinbillal.github.io/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"  # Replace with your actual Google Analytics ID
    measurementID = "G-ZG122SDCV2"  # Replace with your actual Measurement ID